/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : Time,
  'category' : PostCategory,
}
export type PostCategory = { 'theatreNews' : null } |
  { 'interviews' : null } |
  { 'workshops' : null } |
  { 'stageShows' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string, PostCategory], bigint>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'filterPostsByCategory' : ActorMethod<[PostCategory], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPost' : ActorMethod<[bigint], Post>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPosts' : ActorMethod<[], Array<Post>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedPosts' : ActorMethod<[], undefined>,
  'updatePost' : ActorMethod<[bigint, string, string, PostCategory], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];