/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostCategory = IDL.Variant({
  'theatreNews' : IDL.Null,
  'interviews' : IDL.Null,
  'workshops' : IDL.Null,
  'stageShows' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
  'category' : PostCategory,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, PostCategory], [IDL.Nat], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'filterPostsByCategory' : IDL.Func(
      [PostCategory],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedPosts' : IDL.Func([], [], []),
  'updatePost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, PostCategory], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostCategory = IDL.Variant({
    'theatreNews' : IDL.Null,
    'interviews' : IDL.Null,
    'workshops' : IDL.Null,
    'stageShows' : IDL.Null,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
    'category' : PostCategory,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, PostCategory], [IDL.Nat], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'filterPostsByCategory' : IDL.Func(
        [PostCategory],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedPosts' : IDL.Func([], [], []),
    'updatePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, PostCategory],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };